import numpy as np
import pandas as pd
import ta
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from statsmodels.tsa.seasonal import STL
from torch.utils.data import DataLoader, TensorDataset


def load_and_clean_data(path):
    df = pd.read_csv(path)

    # Find missing values in the data
    missing_values = df.isnull().sum()
    print("Missing values in each column:")
    print(missing_values)

    # Fill missing values with previous day's values
    df.fillna(method='ffill', inplace=True)

    return df


def split_series(series, train_ratio=0.8):
    train_size = int(len(series) * train_ratio)
    train, test = series[:train_size], series[train_size:]
    return train, test


def stl_decompose(series, period=252, seasonal=13, robust=True):
    stl = STL(series, period=period, seasonal=seasonal, robust=robust)
    res = stl.fit()
    return res


def compute_returns(series):
    returns = series.pct_change().dropna()
    return returns


def compute_technical_indicators(df):
    # Momentum: RSI (Relative Strength Index)
    rsi_indicator = ta.momentum.RSIIndicator(close=df["Close"], window=14)
    df["RSI_14"] = rsi_indicator.rsi()

    # Volatility: Bollinger Bands
    bb_indicator = ta.volatility.BollingerBands(close=df["Close"], window=20, window_dev=2)
    # Band Width = (Upper - Lower) / Mid
    df["BB_Width"] = (bb_indicator.bollinger_hband() - bb_indicator.bollinger_lband()) / bb_indicator.bollinger_mavg()

    # Volatility: ATR (Average True Range)
    atr_indicator = ta.volatility.AverageTrueRange(high=df["High"], low=df["Low"], close=df["Close"], window=14)
    df["ATR_14"] = atr_indicator.average_true_range()

    # Trend: SMA (Simple Moving Average) & Distance
    sma_indicator = ta.trend.SMAIndicator(close=df["Close"], window=50)
    df["SMA_50"] = sma_indicator.sma_indicator()

    # Distance from SMA (Stationary Feature)
    df["Dist_SMA_50"] = (df["Close"] - df["SMA_50"]) / df["SMA_50"]

    # Volume: OBV (On-Balance Volume)
    obv_indicator = ta.volume.OnBalanceVolumeIndicator(close=df["Close"], volume=df["Volume"])
    df["OBV"] = obv_indicator.on_balance_volume()

    # Drop NaN values generated by the windowing
    df.dropna(inplace=True)

    return df


def add_cyclical_date_features(df):
    # Change date column to features
    df["Date"] = pd.to_datetime(df["Date"])
    df["DayOfWeek"] = df["Date"].dt.dayofweek
    df["Month"] = df["Date"].dt.month
    df["Year"] = df["Date"].dt.year

    # Change cyclical features to sin and cos components
    df['Day_Sin'] = np.sin(2 * np.pi * df['DayOfWeek'] / 7)
    df['Day_Cos'] = np.cos(2 * np.pi * df['DayOfWeek'] / 7)
    df['Month_Sin'] = np.sin(2 * np.pi * df['Month'] / 12)
    df['Month_Cos'] = np.cos(2 * np.pi * df['Month'] / 12)

    return df


# Create training, validation, and testing datasets
def get_train_val_test(data_X, data_y, n_past, n_future):
    X, y = [], []
    for i in range(len(data_X) - n_past - n_future + 1):
        X.append(data_X[i : i + n_past])
        y.append(data_y[i + n_past : i + n_past + n_future])

    X = np.array(X)
    y = np.array(y)

    X_test = X[-1:]
    y_test = y[-1:]

    X_remaining = X[:-1]
    y_remaining = y[:-1]
    # Split remaining data into training and validation sets
    X_train, X_val, y_train, y_val = train_test_split(
        X_remaining, y_remaining,
        test_size=0.2,
        shuffle=False
    )
    return X_train, y_train, X_val, y_val, X_test, y_test


def get_recent_prediction_window(y, n_future, n_past=63, offset=21):
    start = len(y) - n_past - offset
    end = len(y) - offset
    past_data = y[start:end].values

    future_start = len(y) - offset
    future_end = future_start + n_future
    true_future = y.iloc[future_start:future_end].values

    return past_data, true_future


def normalize_datasets(X_train, y_train, X_val, y_val, X_test, y_test, non_cyclical_idx):
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()

    # Fit scalers on training data
    scaler_X.fit(X_train[:, :, non_cyclical_idx].reshape(-1, len(non_cyclical_idx)))
    scaler_y.fit(y_train.reshape(-1, 1))

    for X_data, y_data in [(X_train, y_train), (X_val, y_val), (X_test, y_test)]:
        # Normalize X
        X_data[:, :, non_cyclical_idx] = scaler_X.transform(
            X_data[:, :, non_cyclical_idx].reshape(-1, len(non_cyclical_idx))).reshape(X_data.shape[0], X_data.shape[1], len(non_cyclical_idx)
        )
        # Normalize y
        y_data[:] = scaler_y.transform(y_data.reshape(-1, 1)).reshape(y_data.shape)

    return X_train, y_train, X_val, y_val, X_test, y_test, scaler_X, scaler_y


def normalize_data_correctly(X_train, X_val, X_test, y_train, y_val, y_test, non_cyclical_indices):

    X_train_norm = X_train.copy()
    X_val_norm = X_val.copy()
    X_test_norm = X_test.copy()

    for feature_idx in non_cyclical_indices:

        train_feature = X_train[:, :, feature_idx].flatten()
        scaler = StandardScaler()
        scaler.fit(train_feature.reshape(-1, 1))

        for X_data in [X_train_norm, X_val_norm, X_test_norm]:
            feature_data = X_data[:, :, feature_idx].flatten()
            normalized_data = scaler.transform(feature_data.reshape(-1, 1)).flatten()
            X_data[:, :, feature_idx] = normalized_data.reshape(X_data.shape[0], X_data.shape[1])

    y_scaler = StandardScaler()
    y_scaler.fit(y_train.reshape(-1, 1))

    y_train_norm = y_scaler.transform(y_train.reshape(-1, 1)).reshape(y_train.shape)
    y_val_norm = y_scaler.transform(y_val.reshape(-1, 1)).reshape(y_val.shape)
    y_test_norm = y_scaler.transform(y_test.reshape(-1, 1)).reshape(y_test.shape)

    return X_train_norm, X_val_norm, X_test_norm, y_train_norm, y_val_norm, y_test_norm, y_scaler


def create_dataloaders(X_train, y_train, X_val, y_val, X_test, y_test, batch_size=64, device=None):
    y_train_t = torch.tensor(y_train, dtype=torch.float32)
    y_val_t = torch.tensor(y_val, dtype=torch.float32)
    y_test_t = torch.tensor(y_test, dtype=torch.float32)
    if device is not None:
        y_train_t = y_train_t.to(device)
        y_val_t = y_val_t.to(device)
        y_test_t = y_test_t.to(device)

    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32), y_train_t)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_dataset = TensorDataset(torch.tensor(X_val, dtype=torch.float32), y_val_t)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32), y_test_t)
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

    return train_loader, val_loader, test_loader
